
# Critical Game Analysis

I am going to briefly cover how to do a critical game analysis. However, there are many ways, try to be 
creative.

Some parts of this text is taken from various sources.

References:
- https://ocw.mit.edu/courses/comparative-media-studies-writing/cms-300-introduction-to-videogame-studies-fall-2011/assignments/game-analysis/MITCMS_300F11_GameAnaGuide.pdf
- https://learn.canvas.net/courses/3/pages/level-3-dot-2-critical-analysis-of-games

## First step is selecting a game.

You need to first select a game for this study. Try to select a game that will help you in ideation phase for your project.
It can be because of the graphics, gameplay, controls, theme etc.


## Before you start analysing: play the game

- Play the game extensively

Try to complete the game, or at least familiarize yourself with all the modes. You
should master the game as much as you can. If you've played it before, play it
again, to have the game fresh in your mind—replay always helps achieving new
insights about the game. The time you should be playing the game varies from
game to game. In your analysis, be explicit about how you played the game, if
there are different options (e.g. level of difficulty, character that you used.)

- Take notes while you play.

It's good to keep track of things you come across in the game. What do you like?

What don't you like? Is there something that you did not expect? Does a specific
part of the game remind you of something else (another game, or a movie, or
some other event)? Taking notes of potential examples for your paper is also a
good habit. If you can have a corresponding savegame for reference, even better.

- You can take some help such as walktroughs.

Anyone can get stuck and might need help, especially if it prevents them from
getting far enough in the game (and therefore from playing it extensively). Cheat
codes, watching walkthrough videos, or having a friend play for you are ways to
help you know more about the game, but they should not be the predominant
mode in which you experience it. 

- Read what other people have written about the game



## Contextualize

Providing a frame of reference to understand your analysis is basic to make it
accessible to your reader, particularly if they are not familiar with the game.
Games, like any other media artifacts, are not produced in a void. They are the
product of their times: the technology available at the moment, the people who
made them, or other socio-cultural trends that marked that historical moment.

- Game Developer/Studio; Artists, Designers, Programmers, Writers (or whoever
is relevant).
The creative team of a game is important, particularly in the case where it
connects to other relevant games they worked on before or after this game. Some
development studios or designers have certain trademarks, or specialize on a
particular genre (e.g. Valve, Square Enix or Will Wright), so choosing one of their
games can mark a specific time in the evolution of their games, which might be
important to the context of your analysis.

- Game genre and related games
A game genre usually has a set of established conventions behind it, such as First
Person Shooters, adventure games, real-time strategy games or Role-Playing
Games. Establishing the game within a genre can help determine, for instance,
why it is like other games of the same type, or what is innovative about it. If the
game partakes of conventions from different genres, that can also be a way of
explaining what sets it apart from other games. The relations to other game
genres do not have to be exclusively digital--board and card games, as well as 
other traditional games, can be the origins of certain mechanics.
The game of your choice can relate to other games by any of the elements listed
on these guidelines: developer, genre, publisher, by being released at the same
time, similar mechanics, similar themes (e.g. space flight simulators), being part
of a franchise (e.g. Star Wars or Mario), using similar controls, games that it has
influenced or that later tried to copy it, etc.

- Technological context
What platform(s) was the game developed for? It is important to note which
version of the game you are playing, e.g. Assassin's Creed for the DS is a different
game from the PS3 version. The technology will determine, for instance, the
length of the game or whether there is an ending (think of arcade games in the
early 80s, where games typically did not end). In other cases, such as the Virtual
Boy or the Wii, the technology can also shape the way the way the game is played.

- Socio-historical context
When was the game made? It's different to analyze a game from the 70s, when
videogames were almost exclusively played in arcades, than a recent game, now
that videogames start to enjoy a more general acceptance in cultural terms.
Where was it released? A game released in the US in the mid 80s (after the socalled videogame crash) may not have had the same influence as a game released
in Europe (where videogames were played almost exclusively in home
computers).

- Audience
Who is the game intended for? Games can create communities around them, at
times fostered by the developers themselves. The fans of a particular game can be
a phenomenon worth studying in itself, for example, as creators of content for it,
as critics/reviewers, or as assistants to other players by providing walkthroughs
or strategy guides. Studying the game community in depth can veer away from
the textual analysis provided here, so be aware that if you study the community
you may not be analyzing the game itself. It is a perfectly valid analysis, but
different from the one proposed here.

- Relations to other media
Is the game part of a franchise, a tie-in with a work in another medium (e.g. Lost Via Domus, Wall-E)? Is it an adaptation of the work in another medium, or is it
only using the same characters and settings? Is it inspired by a situation or
premise of another medium (e.g. Dead Rising taking the zombies-in-a-mall
premise of Dawn of the Dead)? Does it incorporate and re-work pre-existing
stories (e.g. Too Human using Norse mythology as the basis for its story, but
transposing it to a high-tech world) Does it use other works as documentation,
background or inspiration (e.g. the writings of Ann Rynd as background
reference to Bioshock)?


## Game Overview

It is always good to explain briefly what you do in the game to someone who has
not played it or is not familiar with it. Do not always take your audience's
knowledge for granted, explain the game to them, so that they are aware of how
you understand it. Give your reader an idea of what gameplay is like.

- No. of Players (single player/multi-player/MMO)

Can you choose the number of players? Does it have different modes depending
on the number of players? If there is more than one player, do they play
simultaneously or do they take turns?

- Rules and goals of the game

Make a summary of the basic rules of the game, a summarized version of the
instructions, as it were. If the game has an end / a win state, what is it? If it does
not, it's also worth explaining whether it is an endless game, or whether there are
multiple goals, or whether the player is able to set their own goals/win state (e.g.

The Sims). Does the game have different modes, where the rules change slightly?

- Description of Gameplay: what do you do in the game?

Focus on the core mechanics: what are the most recurring actions in the game?

You can think of this in terms of verbs: what are the main verbs of the game? For
example, in Super Mario Bros. the verbs would be run, jump, pick up, slide

down, stomp. In Tetris, the verbs would be rotate, drop, clear.

- Spaces of the game

Where does the game take place? How does the player navigate the space? How
does the game encourage exploration of the space, if at all? Are there different
types of spaces, corresponding to different levels? Does the space or navigation
do anything that is not possible in the real world? How does the space of the
game relate to the space of the player?

- Aesthetics: general gameplay experience

This section is a tricky one, since your experience will probably be different from
other people's. Your skills or game knowledge affect the way you play the game.

You can contrast your own gameplay with that of other players by reading
walkthroughs or reviews. You can also compare how you played with the
experience intended by the developers, if you find interviews or postmortems
where they express that intention. Do not try to generalize your opinion--your

experience is valid as long as it is qualified. Do not guess what the intentions of
the game makers are from what you see in the game, you should have factual
evidence, so use concrete examples.

- Rules and Fiction

How is the setting presented outside and in the game? How does the game live up
to it? How does it establish the fictional world of the game? How does it relate to
the rules and goals of the game? If the game has a strong story component, you
may summarize its premise; however, you should avoid turning your analysis
into a retelling of the story of the game.

## Formal Elements

In this section, you have to identify the different game elements that make up the
game system, and establish the relationships between them.

- **Gameworld rules**
What model is the game trying to simulate? How does the gameworld work,
outside of the rules of the game? For instance, San Andreas in Grand Theft Auto:
San Andreas is a city where pedestrians walk on the side walk, cars run at
normal speed on the road and follow traffic rules, and the day/night cycle
changes every 20 minutes. This could be called a simulation of the real world,
within certain limits. Other examples can refer to the difference between what is
possible in the gameworld and what the player is allowed to do. For example, in
the main mode of Halo characters talk to each other in cut-scenes, but the player
cannot choose when to talk or what to say. What is possible or impossible in a
game is the direct result of decisions made in the design of the game, and you
have to be aware of those choices.
- **Simulation and Levels of Abstraction**
What level of abstraction is the game using? How nuanced is the simulation in
the game? For example, Diner Dash simulates the strategic aspects of
waitressing, where the key is to optimize your path to do the most things the least
amount of time, but does not include taking down people's orders and
memorized who ordered what. How complex is the simulation, depending on that
level of abstraction.
- **Game mechanics and resulting dynamics**
From the rules of the game described above, What are the main strategies? What
is their range (i.e. are there just a couple of strategies or is there a wide variety)?
Are there any emergent strategies that are possible but may not have been
predicted by the developers? Does the game accommodate different play styles?
Can the player save the game? If so, can the game be saved at any point, or does
the game regulate when to save the game?
- **The gap between the game and the player: Player character, mediation, interface design**
How does the player have agency in the gameworld? How is the information
displayed on the screen? Is the interaction menu-based (as in Sim City)? Is there
a player character who represents the player in the world? Is it a given character
or is it customizable? Can the player character die or not? Does the player
manipulate the objects directly, without a player character or avatar (e.g. in
puzzle games like Bejeweled)? Can the player select different entities in the world
at a time (as in real-time strategy games)? How is gameplay information 
conveyed through the visuals / audio?
- Difficulty levels and game balancing.
Are there different difficulty levels? How is the level of difficulty increased? Is it
well-balanced, i.e. the game becomes difficult at reasonable increases? What
proficiency does the game expect from the player? Is it easy to pick up, difficult to
master? How does the game teach you how to play it, if at all? Is there a tutorial,
or does the game introduce one new element on each level?

- Control schemes; control peripherals
Does the player have to type the commands of the game? Does it use the mouse/a
game controller/a special peripheral? Does the game allow different ways to
configure your controls? Does the game allow voice input (e.g. voice chat in an
MMO, or voice controls)? How do the controls affect and shape gameplay?

- Audiovisuals: visual design, sound design, music
What is the audiovisual style of the game? Does it evoke / imitate the style of
other media (e.g. painting, photography, cinema, classical music)? Does it use
other games as aesthetic reference (e.g. retro games)? What is the color scheme?
How do these audiovisual elements contribute to the fiction of the game? How do
they contribute to the mood of the game?

- Progression vs Emergence
Does the game force the player to follow a specific sequence? How does the game
guide the player to the correct action? Are there multiple paths? Are there
emergent behaviors, or is there room for emergent gameplay? How does the
game encourage players to experiment with it?

- Mods / Modes / Cheats / Hacks
You may be interested in surveying different gameplay modes, that may not be
the standard for most players, such as user-developed levels, or different modes
of the game (such as the no-fail mode of Rock Band 2, or the crash mode of
Burnout, or the multiplayer modes of Diablo 2). Cheats and game hacks have a
great potential as texts to analyze, since they can become commentaries on the
original game and reveal hidden or non-obvious aspects of the game.

## Round up your discussion
Remember to finish off the paper with a conclusion. Reiterate the main points of
your paper, what you want your reader to remember, the core of your paper in
brief. This is an opportunity to ratify your thesis statement, re-stating it and
summarizing how your evidence supports it. A conclusion can also address one of
the following points, based on your discussion.
- Why is this game relevant to the study of games?
- What is innovative about game? Can it be applied to other games?
- Open up to further questions that need addressing, in videogame theory, game
design, more game analysis, etc. 



